CC = gcc
CLFLAGS = -Wall -Wextra

copy : copy.c
	$(CC) $(CLFLAGS) -o copy copy.c 

gradient : gradient.c
	$(CC) $(CLFLAGS) -o gradient gradient.c 

firstPPM : firstPPM.c
	$(CC) $(CLFLAGS) -o firstPPM firstPPM.c 

clean:
	rm -f firstPPM gradient copy